package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"
	auth "github.com/tiagoposse/entauth"
	"github.com/yourorg/yourapp/ent"
	"github.com/yourorg/yourapp/ent/apikey"
)

// createApiKey generates a new API key with restricted scopes.
// The raw key is returned once and never stored.
func (s *Server) createApiKey(ctx context.Context, _ *ent.Client, request CreateApiKeyRequestObject) (CreateApiKeyResponseObject, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return CreateApiKey401JSONResponse{Error: "authentication required"}, nil
	}

	// Validate that requested scopes are a subset of the user's scopes.
	userScopes := auth.GetScopes(ctx)
	for _, scope := range request.Body.Scopes {
		if scope != "*" && !contains(userScopes, scope) {
			return CreateApiKey400JSONResponse{
				Error: fmt.Sprintf("scope %q not available to your account", scope),
			}, nil
		}
	}

	expiry := time.Duration(request.Body.ExpiryDays) * 24 * time.Hour
	if expiry == 0 {
		expiry = 90 * 24 * time.Hour // default 90 days
	}

	// Generate the token via entauth.
	roles := auth.GetRoles(ctx)
	rawKey, err := s.tokenService.GenerateAPIKey(userID, roles, request.Body.Scopes, expiry)
	if err != nil {
		return nil, fmt.Errorf("generating API key: %w", err)
	}

	// Store metadata in the database (NOT the raw key).
	prefix := rawKey
	if len(prefix) > 12 {
		prefix = prefix[:12]
	}

	record, err := s.client.ApiKey.Create().
		SetUserID(userID).
		SetName(request.Body.Name).
		SetScopes(request.Body.Scopes).
		SetKeyPrefix(prefix).
		SetExpiresAt(time.Now().Add(expiry)).
		Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("saving API key metadata: %w", err)
	}

	return CreateApiKey201JSONResponse(ApiKeyCreated{
		Id:        record.ID,
		Name:      record.Name,
		Key:       rawKey, // returned once, never stored
		Scopes:    record.Scopes,
		ExpiresAt: record.ExpiresAt,
		CreatedAt: record.CreatedAt,
	}), nil
}

// listApiKeys returns the authenticated user's API keys (without raw tokens).
func (s *Server) listApiKeys(ctx context.Context, _ *ent.Client, request ListApiKeysRequestObject) (ListApiKeysResponseObject, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return ListApiKeys401JSONResponse{Error: "authentication required"}, nil
	}

	keys, err := s.client.ApiKey.Query().
		Where(apikey.UserIDEQ(userID), apikey.RevokedAtIsNil()).
		All(ctx)
	if err != nil {
		return nil, err
	}

	items := make([]ApiKeyItem, len(keys))
	for i, k := range keys {
		items[i] = ApiKeyItem{
			Id:         k.ID,
			Name:       k.Name,
			KeyPrefix:  k.KeyPrefix,
			Scopes:     k.Scopes,
			ExpiresAt:  k.ExpiresAt,
			LastUsedAt: k.LastUsedAt,
			CreatedAt:  k.CreatedAt,
		}
	}

	return ListApiKeys200JSONResponse(items), nil
}

// revokeApiKey revokes an API key by ID.
func (s *Server) revokeApiKey(ctx context.Context, _ *ent.Client, request RevokeApiKeyRequestObject) (RevokeApiKeyResponseObject, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return RevokeApiKey401JSONResponse{Error: "authentication required"}, nil
	}

	key, err := s.client.ApiKey.Get(ctx, request.Id)
	if err != nil {
		return RevokeApiKey404JSONResponse{Error: "API key not found"}, nil
	}

	// Only the owner or an admin can revoke.
	if key.UserID != userID && !auth.HasRole(ctx, "admin") {
		return RevokeApiKey403JSONResponse{Error: "not your API key"}, nil
	}

	key.Update().SetRevokedAt(time.Now()).Save(ctx) //nolint:errcheck

	return RevokeApiKey200JSONResponse{Message: fmt.Sprintf("API key %q revoked", key.Name)}, nil
}

func contains(ss []string, s string) bool {
	for _, v := range ss {
		if v == s || v == "*" {
			return true
		}
	}
	return false
}

// Placeholder types — generated by oapi-codegen.
type ApiKeyCreated struct {
	Id        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Key       string    `json:"key"` // returned once at creation
	Scopes    []string  `json:"scopes"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type ApiKeyItem struct {
	Id         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	KeyPrefix  string     `json:"key_prefix"`
	Scopes     []string   `json:"scopes"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	CreatedAt  time.Time  `json:"created_at"`
}

type (
	CreateApiKeyRequestObject       struct{ Body *CreateApiKeyRequest }
	CreateApiKeyRequest             struct{ Name string; Scopes []string; ExpiryDays int }
	CreateApiKey201JSONResponse     ApiKeyCreated
	CreateApiKey400JSONResponse     struct{ Error string }
	CreateApiKey401JSONResponse     struct{ Error string }
	CreateApiKeyResponseObject      interface{ VisitCreateApiKeyResponse(http.ResponseWriter) error }

	ListApiKeysRequestObject        struct{}
	ListApiKeys200JSONResponse      []ApiKeyItem
	ListApiKeys401JSONResponse      struct{ Error string }
	ListApiKeysResponseObject       interface{ VisitListApiKeysResponse(http.ResponseWriter) error }

	RevokeApiKeyRequestObject       struct{ Id uuid.UUID }
	RevokeApiKey200JSONResponse     struct{ Message string }
	RevokeApiKey401JSONResponse     struct{ Error string }
	RevokeApiKey403JSONResponse     struct{ Error string }
	RevokeApiKey404JSONResponse     struct{ Error string }
	RevokeApiKeyResponseObject      interface{ VisitRevokeApiKeyResponse(http.ResponseWriter) error }
)
