//go:build ignore

package api

import (
	"context"
	"net/http"
	"time"

	"github.com/google/uuid"
	auth "github.com/tiagoposse/entauth"
	"github.com/yourorg/yourapp/ent"
	entuser "github.com/yourorg/yourapp/ent/user"
)

// Server wraps the generated EntHandler with auth services.
type Server struct {
	client          *ent.Client
	handler         *EntHandler // generated by entapi
	tokenService    *auth.TokenService
	revocationStore *auth.RevocationStore
}

// NewServer creates a new API server with full auth setup.
func NewServer(client *ent.Client, jwtSecret string) *Server {
	// 1. Create the token service with a role fetcher that reads from the DB.
	tokenService := auth.NewTokenService(
		jwtSecret,
		15*time.Minute,
		func(ctx context.Context, userID uuid.UUID) ([]string, error) {
			u, err := client.User.Get(ctx, userID)
			if err != nil {
				return nil, err
			}
			return []string{string(u.Role)}, nil
		},
	)

	// 2. Map roles to scopes. These are embedded in tokens at generation time,
	// so no DB lookup is needed when checking scopes at request time.
	tokenService.SetScopeResolver(func(roles []string) []string {
		scopeMap := map[string][]string{
			"admin":  {"read", "write", "delete", "users:manage", "api-keys:manage"},
			"editor": {"read", "write"},
			"user":   {"read"},
		}
		var scopes []string
		for _, r := range roles {
			scopes = append(scopes, scopeMap[r]...)
		}
		return scopes
	})

	// 3. Enable token revocation.
	revocationStore := auth.NewRevocationStore()
	tokenService.SetRevocationStore(revocationStore)

	s := &Server{
		client:          client,
		handler:         NewEntHandler(client), // generated
		tokenService:    tokenService,
		revocationStore: revocationStore,
	}
	s.registerCustomHandlers()
	return s
}

// RegisterHandlers wires the generated strict handler with middleware.
func (s *Server) RegisterHandlers(mux *http.ServeMux) {
	authMiddleware := s.strictAuthMiddleware()
	adminMiddleware := s.strictAdminTokenMiddleware()

	strictHandler := NewStrictHandlerWithOptions(
		s.handler,
		[]StrictMiddlewareFunc{authMiddleware, adminMiddleware},
		StrictHTTPServerOptions{
			ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
				if ge, ok := err.(*auth.GuardError); ok {
					http.Error(w, ge.Message, ge.Code)
					return
				}
				http.Error(w, err.Error(), http.StatusInternalServerError)
			},
		},
	)

	HandlerFromMux(strictHandler, mux)
}

// Operations that don't require a valid Bearer token.
var publicOperations = map[string]bool{
	"Login":        true,
	"Register":     true,
	"RefreshToken": true,
}

// strictAuthMiddleware validates Bearer tokens and API keys.
func (s *Server) strictAuthMiddleware() StrictMiddlewareFunc {
	return func(f StrictHandlerFunc, operationID string) StrictHandlerFunc {
		return func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
			if publicOperations[operationID] {
				return f(ctx, w, r, request)
			}

			// Try Bearer token first, then X-API-Key.
			if authHeader := r.Header.Get("Authorization"); authHeader != "" {
				ctx = s.tokenService.ValidateAndSetUser(ctx, authHeader)
			} else if apiKey := r.Header.Get("X-API-Key"); apiKey != "" {
				ctx = s.tokenService.ValidateAPIKey(ctx, apiKey)

				// Update last_used_at for the API key (fire and forget).
				if uid, ok := auth.GetUserID(ctx); ok {
					go s.touchAPIKeyLastUsed(uid, apiKey)
				}
			}

			return f(ctx, w, r, request)
		}
	}
}

// strictAdminTokenMiddleware validates the X-Admin-Token header.
func (s *Server) strictAdminTokenMiddleware() StrictMiddlewareFunc {
	return func(f StrictHandlerFunc, operationID string) StrictHandlerFunc {
		return func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
			ctx = s.tokenService.ValidateAndSetAdmin(ctx, r.Header.Get("X-Admin-Token"))
			return f(ctx, w, r, request)
		}
	}
}

// touchAPIKeyLastUsed updates the last_used_at timestamp for an API key.
func (s *Server) touchAPIKeyLastUsed(userID uuid.UUID, rawKey string) {
	prefix := rawKey
	if len(prefix) > 12 {
		prefix = prefix[:12]
	}
	ctx := context.Background()
	keys, err := s.client.ApiKey.Query().
		Where(/* apikey.UserIDEQ(userID), apikey.KeyPrefixEQ(prefix) */).
		All(ctx)
	if err != nil || len(keys) == 0 {
		return
	}
	keys[0].Update().SetLastUsedAt(time.Now()).Save(ctx) //nolint:errcheck
	_ = userID // used in the Where clause above (pseudo-code)
}

// registerCustomHandlers wires custom auth and API key handlers.
func (s *Server) registerCustomHandlers() {
	// Auth
	customLogin = s.login
	customRegister = s.register
	customRefreshToken = s.refreshToken
	customLogout = s.logout
	customLogoutAll = s.logoutAll
	customAdminElevate = s.adminElevate

	// API keys
	customCreateApiKey = s.createApiKey
	customListApiKeys = s.listApiKeys
	customRevokeApiKey = s.revokeApiKey

	// Sessions
	customListSessions = s.listSessions
	customRevokeSession = s.revokeSession

	// Set owner_id from authenticated user on article creation.
	beforeArticleCreate = func(ctx context.Context, _ *ent.Client, builder *ent.ArticleCreate) error {
		userID, err := auth.RequireAuth(ctx)
		if err != nil {
			return err
		}
		builder.SetOwnerID(userID)
		return nil
	}
}

// adminElevate verifies the admin's password and returns a short-lived token.
func (s *Server) adminElevate(ctx context.Context, _ *ent.Client, request AdminElevateRequestObject) (AdminElevateResponseObject, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return AdminElevate401JSONResponse{Error: "authentication required"}, nil
	}

	u, err := s.client.User.Get(ctx, userID)
	if err != nil {
		return AdminElevate401JSONResponse{Error: "user not found"}, nil
	}
	if u.Role != entuser.RoleAdmin {
		return AdminElevate403JSONResponse{Error: "admin access required"}, nil
	}

	// In production: verify request.Body.Password against u.PasswordHash with bcrypt.

	token, expiresAt := s.tokenService.GenerateAdminToken(userID)
	return AdminElevate200JSONResponse(AdminElevateResponse{
		AdminToken: token,
		ExpiresAt:  expiresAt,
	}), nil
}
