// Example: middleware
//
// Full HTTP middleware stack combining JWT auth, admin elevation,
// API key fallback, and automatic token refresh.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/tiagoposse/authguard"
)

var tokenService *authguard.TokenService

func main() {
	revocationStore := authguard.NewRevocationStore()

	tokenService = authguard.NewTokenService("secret", 15*time.Minute, nil)
	tokenService.SetRevocationStore(revocationStore)
	tokenService.SetScopeResolver(func(roles []string) []string {
		m := map[string][]string{
			"admin":  {"read", "write", "delete", "users:manage"},
			"editor": {"read", "write"},
			"viewer": {"read"},
		}
		var scopes []string
		for _, r := range roles {
			scopes = append(scopes, m[r]...)
		}
		return scopes
	})

	mux := http.NewServeMux()
	mux.HandleFunc("GET /profile", profileHandler)
	mux.HandleFunc("GET /admin/settings", adminSettingsHandler)
	mux.HandleFunc("GET /data", dataHandler)

	// Stack middleware: refresh → auth.
	// RefreshMiddleware runs first so near-expiry tokens get refreshed
	// before the auth middleware validates them.
	handler := chain(
		mux,
		tokenService.RefreshMiddleware(5*time.Minute),
		authStack,
	)

	printDemoTokens()

	fmt.Println("listening on :8080")
	log.Fatal(http.ListenAndServe(":8080", handler))
}

// authStack validates Bearer tokens, API keys, and admin elevation tokens.
func authStack(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		// 1. Try Bearer token (JWT).
		if auth := r.Header.Get("Authorization"); auth != "" {
			ctx = tokenService.ValidateAndSetUser(ctx, auth)
		} else if apiKey := r.Header.Get("X-API-Key"); apiKey != "" {
			// 2. Fall back to API key.
			ctx = tokenService.ValidateAPIKey(ctx, apiKey)
		}

		// 3. Check for admin elevation token.
		if adminToken := r.Header.Get("X-Admin-Token"); adminToken != "" {
			ctx = tokenService.ValidateAndSetAdmin(ctx, adminToken)
		}

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// chain applies middleware in order (last wraps first).
func chain(handler http.Handler, middlewares ...func(http.Handler) http.Handler) http.Handler {
	for i := len(middlewares) - 1; i >= 0; i-- {
		handler = middlewares[i](handler)
	}
	return handler
}

func profileHandler(w http.ResponseWriter, r *http.Request) {
	userID, err := authguard.RequireAuth(r.Context())
	if err != nil {
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}

	tier, _ := authguard.GetSubscriptionTier(r.Context())
	deviceID, _ := authguard.GetDeviceID(r.Context())

	// Check if a refreshed token was generated by the middleware.
	newToken := w.Header().Get("X-Refreshed-Token")

	json.NewEncoder(w).Encode(map[string]interface{}{
		"user_id":        userID,
		"roles":          authguard.GetRoles(r.Context()),
		"scopes":         authguard.GetScopes(r.Context()),
		"subscription":   tier,
		"device":         deviceID,
		"token_refreshed": newToken != "",
	})
}

func adminSettingsHandler(w http.ResponseWriter, r *http.Request) {
	adminID, err := authguard.RequireAdmin(r.Context())
	if err != nil {
		if ge, ok := err.(*authguard.GuardError); ok {
			http.Error(w, ge.Message, ge.Code)
		} else {
			http.Error(w, err.Error(), http.StatusForbidden)
		}
		return
	}

	json.NewEncoder(w).Encode(map[string]interface{}{
		"admin_id": adminID,
		"message":  "you have elevated access",
	})
}

func dataHandler(w http.ResponseWriter, r *http.Request) {
	// Works with both JWT and API key.
	if err := authguard.RequiresScope("read")(r.Context(), nil); err != nil {
		http.Error(w, err.Error(), http.StatusForbidden)
		return
	}

	json.NewEncoder(w).Encode(map[string]string{"data": "some data"})
}

func printDemoTokens() {
	adminID := uuid.MustParse("00000000-0000-0000-0000-000000000001")
	editorID := uuid.MustParse("00000000-0000-0000-0000-000000000002")

	adminAccess, _, _ := tokenService.GenerateTokensWithDevice(adminID, []string{"admin", "sub:enterprise"}, "desktop")
	adminElevation, _ := tokenService.GenerateAdminToken(adminID)
	editorAccess, _, _ := tokenService.GenerateTokens(editorID, []string{"editor", "sub:pro"})
	apiKey, _ := tokenService.GenerateAPIKey(editorID, []string{"service"}, []string{"read"}, 365*24*time.Hour)

	fmt.Println("Demo tokens:")
	fmt.Printf("  admin access:    %s\n", adminAccess)
	fmt.Printf("  admin elevation: %s\n", adminElevation)
	fmt.Printf("  editor access:   %s\n", editorAccess)
	fmt.Printf("  API key (read):  %s\n", apiKey)
	fmt.Println()
	fmt.Println("Try:")
	fmt.Println("  curl localhost:8080/profile -H 'Authorization: Bearer <admin_access>'")
	fmt.Println("  curl localhost:8080/admin/settings -H 'Authorization: Bearer <admin_access>' -H 'X-Admin-Token: <admin_elevation>'")
	fmt.Println("  curl localhost:8080/data -H 'X-API-Key: <api_key>'")
	fmt.Println()
}
