//go:build ignore

package schema

import (
	"time"

	"entgo.io/contrib/entoas"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	auth "github.com/tiagoposse/entauth"
)

// ApiKey persists API key metadata. The actual token is generated by entauth
// and returned once at creation time — it is not stored in the database.
type ApiKey struct {
	ent.Schema
}

func (ApiKey) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New).
			Immutable().
			Annotations(entoas.ReadOnly(true)),
		field.UUID("user_id", uuid.UUID{}).
			Immutable(),
		field.String("name").
			NotEmpty().
			Comment("Human-readable label, e.g. 'CI pipeline'"),
		field.Strings("scopes").
			Comment("Scopes this key is restricted to"),
		field.String("key_prefix").
			MaxLen(12).
			Comment("First 12 chars of the key for identification"),
		field.Time("expires_at"),
		field.Time("last_used_at").
			Optional().
			Nillable(),
		field.Time("revoked_at").
			Optional().
			Nillable().
			Comment("Set when key is revoked; revoked keys fail validation"),
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Annotations(entoas.ReadOnly(true)),
	}
}

func (ApiKey) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
			Ref("api_keys").
			Field("user_id").
			Required().
			Unique().
			Immutable(),
	}
}

func (ApiKey) Annotations() []schema.Annotation {
	return []schema.Annotation{
		// CRUD is handled by custom handlers (create returns the token,
		// list only shows the user's own keys, delete revokes).
		entoas.CreateOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		entoas.ReadOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		entoas.UpdateOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		entoas.DeleteOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		entoas.ListOperation(entoas.OperationPolicy(entoas.PolicyExclude)),
		auth.Guards().
			OnCreate("requiresAuth").
			OnRead("requiresAuth").
			OnDelete("requiresAuth"),
	}
}
